language: julia
julia:
  - 0.4
  - nightly
notifications:
  email: false
before_install:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
script:
  - julia --check-bounds=yes -e 'Pkg.clone(pwd())'
  - julia --check-bounds=yes -e 'Pkg.test("ProjectiveDictionaryPairLearning"; coverage=true)'
after_success:
  - julia -e 'cd(Pkg.dir("ProjectiveDictionaryPairLearning")); using Coverage; Coveralls.submit(Coveralls.process_folder())'
